name: Generate Changelog

on:
  push:
    branches:
      - main
  release:
    types: [created]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Add this for authentication

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit Changelog
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git pull origin main  # Add this to get latest changes
          git add CHANGELOG.md
          git commit -m "Обновление CHANGELOG.md"
          git push origin main  # Simplified push command