name: Build and Test
on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - *

jobs:
  lint:
    strategy:
      matrix:
        go: [ '1.23.4' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Lit by go vet
        run: go vet ./...

      - name: Lint by golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  test:
    strategy:
      matrix:
        go: [ '1.23.4' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Unit tests.
        run: go test -v ./... -coverprofile=coverage.txt

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}